---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/products":
    get:
      summary: Retrieve all products
      tags:
      - Products
      produces:
      - application/json
      responses:
        '200':
          description: products found
          schema:
            type: object
            properties:
              products:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
            required:
            - products
            - status
    post:
      summary: Creates a blog
      tags:
      - Products
      consumes:
      - application/json
      parameters:
      - name: product
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
          required:
          - name
          - description
      responses:
        '200':
          description: product created
  "/api/v1/products/{id}":
    get:
      summary: Retrieves a product
      tags:
      - Products
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: product found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              description:
                type: string
            required:
            - product
