shared:
  aws:
    access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID') { 'please_define_key_id' } %>
    secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCESS_KEY') { 'please_define_access_key' } %>
    region: <%= ENV['AWS_REGION'] %>
    s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>
    s3_asset_url: <%= ENV['AWS_S3_ASSET_URL'] %>
        
development:
  secret_key_base: d69071e75865d955048dda6ed39791bad1746d7884ca9dd57debfe635c2f8ca11ccfb972529d47a31548147b8472b7895cfcfd9f77fed8e3af27869a72a5c99d

test:
  secret_key_base: 9cb051e6f6f402df9955534507012393698011082c0e58f8c71711ed5763f65bf57d094836ac3a09db068f0746a60bccd74f9072c68b4b985c92bab7cc6e77bd

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
